name: Setup Consul Template CLI
description: Downloads and move consul-template binary to the /usr/local/bin/ directory
branding:
  icon: check
  color: blue
inputs:
  version:
    description: Consul Template version to install
    required: false
    default: 0.27.0
runs:
  using: composite
  steps:
    - name: Export vars
      shell: bash
      id: vars
      env:
        RUNNER_OS: ${{ runner.os }}
        VERSION: ${{ inputs.version }}
      run: |
        OS=$(echo "$RUNNER_OS" | tr "[:upper:]" "[:lower:]")

        if [ $OS == "macos" ]; then
          ARCHITECTURE="darwin_amd64"
        elif [ $OS == "linux" ]; then
          ARCHITECTURE="linux_amd64"
        else
          echo "$RUNNER_OS is not supported yet"
          exit 1
        fi

        echo "::set-output name=zip-filename::consul-template_$(echo "$VERSION")_$ARCHITECTURE.zip"

    - name: Download .zip from Hashicorp CDN
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
        ZIP_FILENAME: ${{ steps.vars.outputs.zip-filename }}
      run: wget https://releases.hashicorp.com/consul-template/$VERSION/$ZIP_FILENAME

    - name: Extract .zip file
      shell: bash
      env:
        ZIP_FILENAME: ${{ steps.vars.outputs.zip-filename }}
      run: unzip $ZIP_FILENAME

    - name: Move consul-template binary to /usr/local/bin directory
      run: sudo mv consul-template /usr/local/bin/consul-template
      shell: bash

    - name: Remove residual files
      shell: bash
      env:
        ZIP_FILENAME: ${{ steps.vars.outputs.zip-filename }}
      run: rm -rf $ZIP_FILENAME
