name: Delivery
on:
  push:
    tags-ignore:
      - "*.*"
    branches:
      - next

jobs:
  create_tag_and_release:
    name: Create tag and release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create a GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1
